# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d44e6410dbd5c9f1278e61675e6d1e97350769245435b6370b95417515baa794bb44a79e6cad74e53bd30049bfc1515671e5fc5653d496aeed3fa25f1cb68f95

test:
  secret_key_base: d0f3ee796906ec34a78b7a23059c26ff7e2f5059d8bcffff168ed5e6f98f77905642a134870c012ba4bf3377df331d32818b5767faaafd16d234c849ac0e44ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
